language: node_js
node_js:
  - "10"
  - "8"
addons:
  chrome: stable
cache:
  directories:
    - node_modules
    - .shadow-cljs
    - $HOME/.m2
jobs:
  include:
    - stage: test and build
      script: npm test
    - state: test and build
      script: npm run build
